import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <main className="min-h-screen ">
          {children}
        </main>
        <footer className="bg-blue-50 p-12">
          <div className="container mx-auto px-4 text-center text-gray-600">
            <p>Made with ♥️ by  <Link href="https://x.com/mnraza1907">MN Raza</Link></p>
          </div>
        </footer>
      </body>
    </html>
  );
}
